### ISSUE TITLE
FUSE component breaks git (cannot pread pack file: Bad file descriptor)

### ISSUE THREAD

**Issue by chewi** [immobiliare/sfs#11]
I've hit one or two problems, mainly in php-sync and I'll push those fixes up later, but first I've encountered what I consider to be a showstopper. 

```
$ git fetch
remote: Counting objects: 116, done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 116 (delta 97), reused 0 (delta 0)
Receiving objects: 100% (116/116), 22.44 KiB | 0 bytes/s, done.
fatal: cannot pread pack file: Bad file descriptor
fatal: index-pack failed
```

The same operation works fine on the underlying filesystem. I've tried twiddling various FUSE options but none seem to make any difference. I'm using FUSE 2.9.7 on Gentoo. I've noticed that there are some operations that you have not implemented but none seem to relate to pread.

**Comment by chewi** [comment]
I wondered whether this was a wider FUSE problem so I built their `fusexmp_fh` example, which is quite similar to SFS, and that worked fine.

**Comment by lucabrunox** [comment]
I chewi, SFS is not meant to hold Git repositories, especially because I'm not sure the PHP handles hard links correctly. It's supposed to work with simple files, write them and get them replicated.

However, that pread() failure might also be related to special flags during open(). Not sure how git opened the files there.

**Comment by chewi** [comment]
Thanks, your suggestion helped me to figure it out. I had been comparing SFS and fusexmp_fh but hadn't noticed the difference in the way files are created until now.

SFS:
```c
fd = creat(fpath, mode);
```

fusexmp_fh:
```c
fd = open(path, fi->flags, mode);
```

The latter works. I will include this in a pull request soon.

There are a number of other small differences between SFS and [fusexmp_fh](https://github.com/libfuse/libfuse/blob/fuse-2.9.7/example/fusexmp_fh.c) for which I can see no obvious reason. For example, fusexmp_fh also handles pipes (`mkfifo`) in the mknod handler and it uses `lchown` rather than `chown` in the chown handler. Perhaps we should follow fusexmp_fh more closely. What do you think?

I can appreciate that SFS wasn't designed to handle git repositories but I have come here after trying GlusterFS (too slow), OriFS (unmaintained, poorly documented, didn't work, very unstable), and MooseFS (unsuitable for 2 nodes). I am rather desperate at this point. It would only be me working on these files so I do not expect both sides to be modified at the same time.

I am aware that git uses hard links so I did grab @mokraemer's fix for hard links but haven't vet verified whether this works.
