### ISSUE TITLE
PHP Error in sync.php

### ISSUE THREAD

**Issue by faridz88** [immobiliare/sfs#9]
Hi
After running `sync.php` using php-cli i get this error:
```bash
sfs-sync(main)[25086]: PHP Fatal error:  Call to undefined function msg_get_queue() in /home/sfs/sfs/php-sync/sync.php on line 144

Fatal error: Call to undefined function msg_get_queue() in /home/sfs/sfs/php-sync/sync.php on line 144
```

And i see `msg_get_queue()` has not defined before.

**Comment by rafalo79** [comment]
Hi faridz88,
see this link:
http://www.php.net/manual/en/sem.installation.php

**Comment by faridz88** [comment]
I didn't notice that `msg_get_queue()` is a PHP core function. Cause I am not a PHP guy!
Thanks for the link. My problem has been solved. It would be better to add it to System Requirements on README because it is not enabled by default.
